# Generated by Django 5.2.1 on 2025-05-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0002_alter_blog_status_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='section',
            field=models.CharField(choices=[('Trending', 'Trending'), ('Popular', 'Popular'), ('Recent', 'Recent')], max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('1', 'PUBLISH'), ('0', 'DRAFT')], default=0, max_length=1),
        ),
    ]
