# Generated by Django 5.2.1 on 2025-05-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0006_blog_views_alter_blog_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='section',
            field=models.CharField(choices=[('Recent', 'Recent'), ('Popular', 'Popular'), ('Trending', 'Trending'), ('EditorsPick', 'EditorsPick')], max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('0', 'DRAFT'), ('1', 'PUBLISH')], default='0', max_length=1),
        ),
    ]
