# Generated by Django 5.2.1 on 2025-05-18 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0007_alter_blog_section_alter_blog_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_guest', models.BooleanField(default=False, help_text='Check if this is a guest author.')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='author_images')),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='section',
            field=models.CharField(choices=[('Recent', 'Recent'), ('Popular', 'Popular'), ('Trending', 'Trending'), ('EditorsPick', 'EditorsPick'), ('Inspiration', 'Inspiration'), ('Celebration', 'Celebration')], max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='HOME.author'),
        ),
    ]
